### ISSUE TITLE
Project status update in README?

### ISSUE THREAD

**Issue by jonathancross** [Sharpiro/go-slip-0039#6]
I see that in the README, you state:

> "...neither the SLIP nor this codebase is certified for use at this time."

Considering the Trezor firmware now has full support for SLIP-39 and the 2 issues mentioned ([#497](https://github.com/satoshilabs/slips/issues/497) and [#501](https://github.com/satoshilabs/slips/issues/501)) have been resolved, it would be great to update the status of this project.

Perhaps any remaining problems / missing features in your implementation can be turned into new github issues?  This would increase visibility and give others the opportunity to fix / discuss.

Thanks!

**Comment by Sharpiro** [comment]
Hi, I think that since the SLIP has progressed so much, and there are several working implementations by Trezor and now by others, I'm just going to archive this repo since its original purpose was to provide feedback on the SLIP when there wasn't much activity.  Thanks.

**Comment by Sharpiro** [comment]
For now, I've updated the readme to point to the official reference implementations
